INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2018","Dodge","Charger Hellcat","V8 Manual","20000","Excellent");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2018","BMW","M850i","V8 Dual-Clutch Automatic","3000","New");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2018","Mercedes-Benz","SLS AMG","V8 Dual-Clutch Automatic","10000","Excellent");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2018","Porsche","991","V6 Manual","15000","Excellent");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2018","Chevrolet","Corvette Z06","V8 Manual","25000","Excellent");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2018","Telsa","Model X","100D Single Speed Transaxle","13500","New");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2018","Bentley","Continental GT","V8 Automatic","5000","New");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2017","Lamborgini","Aventador S","V12 Automatic","1000","New");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2017","McLaren","650 S","V8 Dual-Clutch Automatic","12000","Excellent");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2017","Maserati","Ghibli","V6 Automatic","30000","Excellent");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2017","Rolls Royce","Phantom","V8 Automatic","26000","Excellent");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2017","Ferrari","458 Italia","V8 Dual-Clutch Automatic","23000","Excellent");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2017","Alfa Romeo","Giulia","V6 Manual","2000","New");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2017","Bugatti","Veyron Grand Sport","W16 Dual-Clutch Automatic","8000","New");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2017","Aston Martin","Rapide","V12 Dual-Clutch Automatic","4500","Excellent");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2016","Hummer","H2","V8 Automatic","32000","Excellent");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2016","Jaguar","F-Type","V8 SuperChargerd Dual-Clutch Automatic","20000","Excellent");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2016","Land Rover","Range Rover Velar","V6 Automatic","24000","Excellent");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2016","Audi","R8","V8 Manual","40000","Good");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2016","Dodge","Challenger","V8 Automatic","38000","Good");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2016","Lotus","Elise","V6 Automatic","45000","Good");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2016","Nissan","GTR","V6 Dual-Clutch Automatic","39000","Excellent");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2016","Acura","NSX","V6 Automatic","36500","Good");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2015","Audi","RS5","V6 Automatic","52000","Good");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2015","Mercedes-Benz","AMG GT","V12 Dual-Clutch Automatic","43500","Good");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2015","Lamborgini","Gallardo","V10 Automatic","47500","Excellent");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2015","Maserati","Quattroporte","V8 Automatic","50000","Good");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2015","Alfa Romeo","Giulia","V6 Automatic","45000","Good");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2015","BMW","750i","V12 Automatic","58000","Good");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2015","Bugatti","Veyron","V12 Automatic","64000","Good");
INSERT INTO cars (car_Year,car_Make,car_Model,transmission_Type,car_Miles,car_Condition) VALUES ("2015","Ferrai","488","V8 Dual-Clutch Automatic","53000","Good");
